### ISSUE TITLE
DefaultRV32Config build problem 

### ISSUE THREAD

**Issue by esolera** [freechipsproject/rocket-chip#1010]
I tried to build them a run it benchmarks with this instruction from emulator file :
make CONFIG=DefaultRV32Config -j1 run-bmark-tests
mkdir -p /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/emulator/generated-src/
cd /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip && java -Xmx2G -Xss8M -XX:MaxPermSize=256M -jar /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/sbt-launch.jar "run-main freechips.rocketchip.system.Generator /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/emulator/generated-src freechips.rocketchip.system TestHarness freechips.rocketchip.system DefaultRV32Config"
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[info] Loading project definition from /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/project
Using addons: 
[info] Set current project to rocketchip (in build file:/home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/)
[info] Compiling 1 Scala source to /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/chisel3/target/scala-2.11/classes...
[info] Packaging /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/chisel3/target/scala-2.11/chisel3_2.11-3.1-SNAPSHOT.jar ...
[info] Done packaging.
[info] Running freechips.rocketchip.system.Generator /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/emulator/generated-src freechips.rocketchip.system TestHarness freechips.rocketchip.system DefaultRV32Config
[info] [0.030] Elaborating design...
[error] (run-main-0) java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at freechips.rocketchip.util.HasGeneratorUtilities$$anonfun$2.apply(GeneratorUtils.scala:50)
	at freechips.rocketchip.util.HasGeneratorUtilities$$anonfun$2.apply(GeneratorUtils.scala:47)
	at chisel3.core.Module$.do_apply(Module.scala:42)
	at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:92)
	at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:92)
	at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:240)
	at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:238)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at chisel3.internal.Builder$.build(Builder.scala:238)
	at chisel3.Driver$.elaborate(Driver.scala:92)
Caused by: java.lang.IllegalArgumentException: requirement failed: Xbar data widths don't match: List(ExampleRocketSystem) has 8B vs List(plic, clint, dmInner, bootrom) has 4B
	at scala.Predef$.require(Predef.scala:219)
	at freechips.rocketchip.tilelink.TLXbar$$anonfun$12$$anonfun$15.apply(Xbar.scala:33)
	at freechips.rocketchip.tilelink.TLXbar$$anonfun$12$$anonfun$15.apply(Xbar.scala:32)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at freechips.rocketchip.tilelink.TLXbar$$anonfun$12.apply(Xbar.scala:32)
	at freechips.rocketchip.tilelink.TLXbar$$anonfun$12.apply(Xbar.scala:26)
	at freechips.rocketchip.diplomacy.MixedNexusNode.mapParamsU(Nodes.scala:348)
	at freechips.rocketchip.diplomacy.MixedNode.iParams$lzycompute(Nodes.scala:208)
	at freechips.rocketchip.diplomacy.MixedNode.iParams(Nodes.scala:207)
	at freechips.rocketchip.diplomacy.MixedNode.edgesIn$lzycompute(Nodes.scala:217)
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2081)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2081)
	at scala.Option.foreach(Option.scala:236)
	at sbt.BuildCommon$class.toError(Defaults.scala:2081)
	at sbt.Defaults$.toError(Defaults.scala:39)
	at sbt.Defaults$$anonfun$runMainTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defaults.scala:740)
	at sbt.Defaults$$anonfun$runMainTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defaults.scala:738)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error] (rocketchip/compile:runMain) Nonzero exit code: 1
[error] Total time: 29 s, completed Sep 21, 2017 11:10:29 AM
make: Nothing to be done for 'run-bmark-tests'.

**Comment by esolera** [comment]
I make a clean and tried again, this is the error now : 

Set current project to rocketchip (in build file:/home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/)
[info] Compiling 1 Scala source to /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/chisel3/target/scala-2.11/classes...
[info] Packaging /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/chisel3/target/scala-2.11/chisel3_2.11-3.1-SNAPSHOT.jar ...
[info] Done packaging.
[info] Compiling 1 Scala source to /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/target/scala-2.11/classes...
[error] /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/src/main/scala/system/Configs.scala:20: value x is not a member of StringContext
[error]                       base = x"8000_0000",
[error]                              ^
[error] /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/src/main/scala/system/Configs.scala:21: value x is not a member of StringContext
[error]                       size = x"1000_0000",
[error]                              ^
[error] /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/src/main/scala/system/Configs.scala:22: not found: value MemoryBusKey
[error]                       beatBytes = site(MemoryBusKey).beatBytes,
[error]                                        ^
[error] /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/src/main/scala/system/Configs.scala:25: value x is not a member of StringContext
[error]                       base = x"6000_0000",
[error]                              ^
[error] /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/src/main/scala/system/Configs.scala:26: value x is not a member of StringContext
[error]                       size = x"2000_0000",
[error]                              ^
[error] /home/edgar/Desktop/RISCV_FOLDERS/rocket-chip/src/main/scala/system/Configs.scala:27: not found: value MemoryBusKey
[error]                       beatBytes = site(MemoryBusKey).beatBytes,
[error]                                        ^
[error] 6 errors found
[error] (rocketchip/compile:compileIncremental) Compilation failed
[error] Total time: 16 s, completed Sep 22, 2017 10:31:15 AM
make: Nothing to be done for 'run-bmark-tests'.

**Comment by esolera** [comment]
I reinstall the tool rocketchip and now its okey.
