### ISSUE TITLE
Delete icache or shrink it to 1 line and bypass icache

### ISSUE THREAD

**Issue by xiwangwl** [freechipsproject/rocket-chip#1381]
I want to delete the icache to shrink size. And I got the information that icache cannot be deleted. 
I start to config it to be 1 line. What I change is the file src/main/scala/subsystem/Configs.scala:line 91
      icache = Some(ICacheParams(
        rowBits = site(SystemBusKey).beatBits,
        nSets = 1,
        nWays = 1,
        nTLBEntries = 4,
        blockBytes = site(CacheBlockBytes)))))

And it report errors:
Using addons: 
[info] Set current project to rocketchip (in build file:/root/riscv/freedom/rocket-chip/)
[info] Compiling 1 Scala source to /root/riscv/freedom/rocket-chip/target/scala-2.11/classes ...
[info] Done compiling.
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Packaging /root/riscv/freedom/rocket-chip/target/scala-2.11/rocketchip_2.11-1.2.jar ...
[info] Done packaging.
[info] Running freechips.rocketchip.system.Generator /root/riscv/freedom/rocket-chip/vsim/generated-src freechips.rocketchip.system TestHarness freechips.rocketchip.system TinyConfig
[info] [0.012] Elaborating design...
Interrupt map (1 harts 2 interrupts):
  [1, 2] => dut

[error] (run-main-0) java.lang.reflect.InvocationTargetException
[error] java.lang.reflect.InvocationTargetException
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] 	at freechips.rocketchip.util.HasGeneratorUtilities$$anonfun$2.apply(GeneratorUtils.scala:52)
[error] 	at freechips.rocketchip.util.HasGeneratorUtilities$$anonfun$2.apply(GeneratorUtils.scala:49)
[error] 	at chisel3.core.Module$.do_apply(Module.scala:47)
[error] 	at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:92)
[error] 	at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:92)
[error] 	at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:275)
[error] 	at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:273)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error] 	at chisel3.internal.Builder$.build(Builder.scala:273)
[error] 	at chisel3.Driver$.elaborate(Driver.scala:92)
[error] 	at freechips.rocketchip.util.HasGeneratorUtilities$class.elaborate(GeneratorUtils.scala:55)
[error] 	at freechips.rocketchip.system.Generator$.elaborate(Generator.scala:12)
[error] 	at freechips.rocketchip.util.GeneratorApp$class.circuit(GeneratorUtils.scala:92)
[error] 	at freechips.rocketchip.system.Generator$.circuit$lzycompute(Generator.scala:12)
[error] 	at freechips.rocketchip.system.Generator$.circuit(Generator.scala:12)
[error] 	at freechips.rocketchip.util.GeneratorApp$class.generateFirrtl(GeneratorUtils.scala:98)
[error] 	at freechips.rocketchip.system.Generator$.generateFirrtl(Generator.scala:12)
[error] 	at freechips.rocketchip.system.Generator$.delayedEndpoint$freechips$rocketchip$system$Generator$1(Generator.scala:88)
[error] 	at freechips.rocketchip.system.Generator$delayedInit$body.apply(Generator.scala:12)
[error] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] 	at scala.App$class.main(App.scala:76)
[error] 	at freechips.rocketchip.system.Generator$.main(Generator.scala:12)
[error] 	at freechips.rocketchip.system.Generator.main(Generator.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.IllegalArgumentException: requirement failed
[error] 	at scala.Predef$.require(Predef.scala:212)
[error] 	at chisel3.util.log2Ceil$.apply(Math.scala:21)
[error] 	at chisel3.util.log2Ceil$.apply(Math.scala:24)
[error] 	at freechips.rocketchip.rocket.ICacheModule$$anonfun$17.apply(ICache.scala:123)
[error] 	at freechips.rocketchip.rocket.ICacheModule$$anonfun$17.apply(ICache.scala:123)
[error] 	at scala.Option.map(Option.scala:146)
[error] 	at freechips.rocketchip.rocket.ICacheModule.<init>(ICache.scala:123)
[error] 	at freechips.rocketchip.rocket.ICache.module$lzycompute(ICache.scala:49)
[error] 	at freechips.rocketchip.rocket.ICache.module(ICache.scala:49)
[error] 	at freechips.rocketchip.rocket.ICache.module(ICache.scala:48)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156)
[error] 	at chisel3.core.Module$.do_apply(Module.scala:47)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:156)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:154)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:338)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$class.instantiate(LazyModule.scala:154)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImp.instantiate(LazyModule.scala:183)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImp.<init>(LazyModule.scala:184)
[error] 	at freechips.rocketchip.rocket.FrontendModule.<init>(Frontend.scala:72)
[error] 	at freechips.rocketchip.rocket.Frontend.module$lzycompute(Frontend.scala:59)
[error] 	at freechips.rocketchip.rocket.Frontend.module(Frontend.scala:59)
[error] 	at freechips.rocketchip.rocket.Frontend.module(Frontend.scala:58)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156)
[error] 	at chisel3.core.Module$.do_apply(Module.scala:47)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:156)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:154)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:338)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$class.instantiate(LazyModule.scala:154)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImp.instantiate(LazyModule.scala:183)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImp.<init>(LazyModule.scala:184)
[error] 	at freechips.rocketchip.tile.BaseTileModuleImp.<init>(BaseTile.scala:173)
[error] 	at freechips.rocketchip.tile.RocketTileModuleImp.<init>(RocketTile.scala:98)
[error] 	at freechips.rocketchip.tile.RocketTile.module$lzycompute(RocketTile.scala:95)
[error] 	at freechips.rocketchip.tile.RocketTile.module(RocketTile.scala:95)
[error] 	at freechips.rocketchip.tile.RocketTile.module(RocketTile.scala:34)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156)
[error] 	at chisel3.core.Module$.do_apply(Module.scala:47)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:156)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:154)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:338)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$class.instantiate(LazyModule.scala:154)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImp.instantiate(LazyModule.scala:183)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImp.<init>(LazyModule.scala:184)
[error] 	at freechips.rocketchip.subsystem.BareSubsystemModuleImp.<init>(BaseSubsystem.scala:19)
[error] 	at freechips.rocketchip.subsystem.BaseSubsystemModuleImp.<init>(BaseSubsystem.scala:100)
[error] 	at freechips.rocketchip.subsystem.RocketSubsystemModuleImp.<init>(RocketSubsystem.scala:154)
[error] 	at freechips.rocketchip.system.ExampleRocketSystemModuleImp.<init>(ExampleRocketSystem.scala:22)
[error] 	at freechips.rocketchip.system.ExampleRocketSystem.module$lzycompute(ExampleRocketSystem.scala:19)
[error] 	at freechips.rocketchip.system.ExampleRocketSystem.module(ExampleRocketSystem.scala:19)
[error] 	at freechips.rocketchip.system.TestHarness$$anonfun$1.apply(TestHarness.scala:14)
[error] 	at freechips.rocketchip.system.TestHarness$$anonfun$1.apply(TestHarness.scala:14)
[error] 	at chisel3.core.Module$.do_apply(Module.scala:47)
[error] 	at freechips.rocketchip.system.TestHarness.<init>(TestHarness.scala:14)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] 	at freechips.rocketchip.util.HasGeneratorUtilities$$anonfun$2.apply(GeneratorUtils.scala:52)
[error] 	at freechips.rocketchip.util.HasGeneratorUtilities$$anonfun$2.apply(GeneratorUtils.scala:49)
[error] 	at chisel3.core.Module$.do_apply(Module.scala:47)
[error] 	at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:92)
[error] 	at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:92)
[error] 	at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:275)
[error] 	at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:273)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error] 	at chisel3.internal.Builder$.build(Builder.scala:273)
[error] 	at chisel3.Driver$.elaborate(Driver.scala:92)
[error] 	at freechips.rocketchip.util.HasGeneratorUtilities$class.elaborate(GeneratorUtils.scala:55)
[error] 	at freechips.rocketchip.system.Generator$.elaborate(Generator.scala:12)
[error] 	at freechips.rocketchip.util.GeneratorApp$class.circuit(GeneratorUtils.scala:92)
[error] 	at freechips.rocketchip.system.Generator$.circuit$lzycompute(Generator.scala:12)
[error] 	at freechips.rocketchip.system.Generator$.circuit(Generator.scala:12)
[error] 	at freechips.rocketchip.util.GeneratorApp$class.generateFirrtl(GeneratorUtils.scala:98)
[error] 	at freechips.rocketchip.system.Generator$.generateFirrtl(Generator.scala:12)
[error] 	at freechips.rocketchip.system.Generator$.delayedEndpoint$freechips$rocketchip$system$Generator$1(Generator.scala:88)
[error] 	at freechips.rocketchip.system.Generator$delayedInit$body.apply(Generator.scala:12)
[error] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] 	at scala.App$class.main(App.scala:76)
[error] 	at freechips.rocketchip.system.Generator$.main(Generator.scala:12)
[error] 	at freechips.rocketchip.system.Generator.main(Generator.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:124)
[error] 	at sbt.Run.run(Run.scala:77)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1147)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1142)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 125 s, completed Apr 27, 2018 12:53:45 PM
make: *** [/root/riscv/freedom/rocket-chip/vsim/generated-src/freechips.rocketchip.system.TinyConfig.fir] Error 1

**Comment by mayoru** [comment]
It seems that the requirement at  [https://github.com/freechipsproject/rocket-chip/blob/master/src/main/scala/rocket/ICache.scala](url) is failed (line 123):
 require(!usingVM || pgIdxBits >= untagBits)
Try disabling virtual memory (useVM = false)
