### ISSUE TITLE
error: java.util.NoSuchElementException:head of empty stream

### ISSUE THREAD

**Issue by IC-Dream** [freechipsproject/rocket-chip#1538]
Hi,

After installing the toolchain successfully, I entered the directory of emulator to build the C simulator by "make", but i got the following error:

[error] java.util.NoSuchElementException: head of empty stream
[error] 	at scala.collection.immutable.Stream$Empty$.head(Stream.scala:1104)
[error] 	at scala.collection.immutable.Stream$Empty$.head(Stream.scala:1102)
[error] 	at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$21(SbtGit.scala:138)
[error] 	at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:810)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:202)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:219)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.util.NoSuchElementException: head of empty stream
[error] Use 'last' for the full log

Any help will be appreciated.

Thanks

**Comment by IC-Dream** [comment]
@ucbjrl Could you please help me take a look? the version of firrtl is the current commit(547082c04886f605b6f411b4ff3e42b54062f9a0), thanks so much.

**Comment by IC-Dream** [comment]
See solution in freechipsproject/rocket-chip#1041
