### ISSUE TITLE
Increase external AXI bus width

### ISSUE THREAD

**Issue by mmckeown** [freechipsproject/rocket-chip#1683]
**Type of issue**: bug report

**Impact**: unknown

**Development Phase**: request

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

1. Modify `src/main/scala/system/Configs.scala:24` from

    `class DefaultConfig extends Config(new WithNBigCores(1) ++ new BaseConfig)`

    to

    `class DefaultConfig extends Config(new WithEdgeDataBits(256) ++ new WithNBigCores(1) ++ new BaseConfig)`

2. `cd vsim; make`

**What is the current behavior?**

firrtl command produces the following exception:

```
Exception in thread "main" firrtl.passes.PassExceptions:
firrtl.passes.CheckWidths$BitsWidthException:  @[Fragmenter.scala 67:27:freechips.rocketchip.system.DefaultConfig.fir@220495.4]: [module AXI4Fragmenter_2] High bit 7 in bits operator is larger than input width 7 in bits(_T_242, 7, 0).
firrtl.passes.CheckWidths$BitsWidthException:  @[Fragmenter.scala 67:27:freechips.rocketchip.system.DefaultConfig.fir@220625.4]: [module AXI4Fragmenter_2] High bit 7 in bits operator is larger than input width 7 in bits(_T_342, 7, 0).
firrtl.passes.PassException: 2 errors detected!
        at firrtl.passes.Errors.trigger(Passes.scala:45)
        at firrtl.passes.CheckWidths$.run(CheckWidths.scala:112)
        at firrtl.passes.Pass.execute(Passes.scala:24)
        at firrtl.passes.Pass.execute$(Passes.scala:22)
        at firrtl.passes.CheckWidths$.execute(CheckWidths.scala:11)
        at firrtl.Transform.$anonfun$runTransform$2(Compiler.scala:257)
        at firrtl.Utils$.time(Utils.scala:182)
        at firrtl.Transform.runTransform(Compiler.scala:257)
        at firrtl.SeqTransformBased.$anonfun$runTransforms$1(Compiler.scala:309)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
        at scala.collection.immutable.List.foldLeft(List.scala:86)
        at firrtl.SeqTransformBased.runTransforms(Compiler.scala:309)
        at firrtl.SeqTransformBased.runTransforms$(Compiler.scala:308)
        at firrtl.SeqTransform.runTransforms(Compiler.scala:313)
        at firrtl.SeqTransform.execute(Compiler.scala:319)
        at firrtl.Transform.$anonfun$runTransform$2(Compiler.scala:257)
        at firrtl.Utils$.time(Utils.scala:182)
        at firrtl.Transform.runTransform(Compiler.scala:257)
        at firrtl.Compiler.$anonfun$compile$2(Compiler.scala:471)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
        at scala.collection.immutable.List.foldLeft(List.scala:86)
        at firrtl.Compiler.$anonfun$compile$1(Compiler.scala:471)
        at firrtl.Utils$.time(Utils.scala:182)
        at firrtl.Compiler.compile(Compiler.scala:471)
        at firrtl.Compiler.compile$(Compiler.scala:467)
        at firrtl.VerilogCompiler.compile(LoweringCompilers.scala:149)
        at firrtl.Driver$.$anonfun$execute$1(Driver.scala:241)
        at logger.Logger$.$anonfun$makeScope$2(Logger.scala:138)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at logger.Logger$.makeScope(Logger.scala:136)
        at firrtl.Driver$.execute(Driver.scala:223)
        at firrtl.Driver$.execute(Driver.scala:301)
        at firrtl.Driver$.main(Driver.scala:317)
        at firrtl.Driver.main(Driver.scala)
```

**What is the expected behavior?**

Compilation successfully finishes and produces a system with a 256-bit external interface.  Tests can successfully run on the system.

**Please tell us about your environment:**

- version: `4f9f3f4f9958c9a667f48ad9791ab3ab3c4e0ee7`
- OS: `CentOS Linux release 7.5.1804`
- With no changes compilation succeeds and tests pass

**What is the use case for changing the behavior?**

Would like to increase the external memory interface bit width to provide more memory bandwidth to the system.  Setting the external memory interface bit width with `WithEdgeDataBits` to anything above 128-bits fails due to an issue in AXI4Fragmenter where an index into an address exceeds the overall bit width of the address.  The address index is dependent on beatBytes.  Printing out the slave.maxAddress in the AXI4Fragmenter seems to print addresses corresponding to devices that should not see this change in bit width (debug-controller and interrupt-controller devices).  However, printing out lgBytes shows that they are seeing this bit width change. These devices sit on buses internal to the system where the bit width is unchanged.  The debug-controller specifically is the device that causes the exception since its maxAddress can be represented with only 12-bits.  The shifting of this address by lgBytes produces a resulting bit vector that is too small to be indexed by the AXI len parameter (set to 8).

**Comment by terpstra** [comment]
The problem is not what you explain above.

The problem is that the AXIMMIO simulation memory is only 4kB which is not larger than a full-sized AXI burst with a 256-bit bus.

In src/main/scala/subsystem/Ports.scala, change:
```
-      val mmio_mem = LazyModule(new SimAXIMem(edge, size = 4096))
+      val mmio_mem = LazyModule(new SimAXIMem(edge, size = 4096*2))
```

However, we probably want the AXI4Fragmenter to work also in this case, so I'll fix it instead.
